"""Public-key store for the corpus's Ed25519 signer identities.

Every `signer_key_id` string in the corpus (a `did:key:...`-shaped opaque
identifier — see docs/phases/01-synthetic-data.md §2.1) is a lookup key into
this store, not a self-describing multicodec key the way a real did:key
would be. That's a deliberate simplification: this project's registry is
already the source of truth for identity (CLAUDE.md "Registry" decision), so
a keystore lookup is the natural fit, and it avoids rewriting every id
string in the corpus to embed real key bytes.

Private keys are never persisted — scripts/sign_corpus.py holds them only
in memory for the duration of a signing run. Losing them just means the
next run mints fresh keys and re-signs the whole corpus; nothing downstream
depends on key material being stable across runs.
"""
from __future__ import annotations

import base64
import json
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

KEYSTORE_PATH = Path(__file__).resolve().parent / "registry" / "keystore.json"


def save_public_keys(public_keys: dict[str, Ed25519PublicKey]) -> None:
    from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

    payload = {
        "description": (
            "Public keys for every signer_key_id in the corpus. "
            "Regenerated by scripts/sign_corpus.py; private keys are never persisted."
        ),
        "keys": {
            key_id: {
                "alg": "Ed25519",
                "public_key": base64.b64encode(
                    pub.public_bytes(Encoding.Raw, PublicFormat.Raw)
                ).decode("ascii"),
            }
            for key_id, pub in sorted(public_keys.items())
        },
    }
    KEYSTORE_PATH.parent.mkdir(parents=True, exist_ok=True)
    KEYSTORE_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def load_public_keys() -> dict[str, Ed25519PublicKey]:
    data = json.loads(KEYSTORE_PATH.read_text(encoding="utf-8"))
    return {
        key_id: Ed25519PublicKey.from_public_bytes(base64.b64decode(entry["public_key"]))
        for key_id, entry in data["keys"].items()
    }
